### ISSUE TITLE
MediaTimeEvents and showBackground issue

### ISSUE THREAD

**Issue by nicosang** [sandflow/imscJS#1]
Hi,

I try to parse this subtitles :

<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns="http://www.w3.org/ns/ttml"
    xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ttm="http://www.w3.org/ns/ttml#metadata"
    xmlns:ebuttm="urn:ebu:metadata" xmlns:ebutts="urn:ebu:style"
    xml:lang="eng" xml:space="default"
    ttp:timeBase="media"
    ttp:cellResolution="32 15">
  <head>
    <metadata>
      <ttm:title>DASH-IF Live Simulator</ttm:title>
      <ebuttm:documentMetadata>
        <ebuttm:conformsToStandard>urn:ebu:distribution:2014-01</ebuttm:conformsToStandard>
        <ebuttm:authoredFrameRate>30</ebuttm:authoredFrameRate>
      </ebuttm:documentMetadata>
    </metadata>
    <styling>
      <style xml:id="s0" tts:fontStyle="normal" tts:fontFamily="sansSerif" tts:fontSize="100%" tts:lineHeight="normal"
      tts:color="#FFFFFF" tts:wrapOption="noWrap" tts:textAlign="center"/>
      <style xml:id="s1" tts:color="#00FF00" tts:backgroundColor="#000000" ebutts:linePadding="0.5c"/>
      <style xml:id="s2" tts:color="#ff0000" tts:backgroundColor="#000000" ebutts:linePadding="0.5c"/>
    </styling>
    <layout>
      <region xml:id="r0" tts:origin="15% 80%" tts:extent="70% 20%" tts:overflow="visible" tts:displayAlign="before"/>
      <region xml:id="r1" tts:origin="15% 20%" tts:extent="70% 20%" tts:overflow="visible" tts:displayAlign="before"/>
    </layout>
  </head>
  <body style="s0">
    <div region="r0">
      
      <p xml:id="sub02000" begin="00:00:02.000" end="00:00:03.000" >
        <span style="s1">eng : 00:00:02.000</span>
      </p>
      
      <p xml:id="sub03000" begin="00:00:03.000" end="00:00:04.000" >
        <span style="s1">eng : 00:00:03.000</span>
      </p>
      
    </div>
  </body>
</tt>

For it, I call first the function fromXML(), then I call getMediaEvents(). The returned arrays contains [0,2,3,4]. I don't understand the 0 value. Could someone help me? Perhaps, it's not an issue, just a misunderstanding... :-) 

Thanks,
Nicolas

**Comment by palemieux** [comment]
When media timebase is active (as is always the case with IMSC1 and EBU-TT-D), the timeline extends from 0 to +infinity. The array returned by getMediaEvents() covers this timeline in its entirety, with each element indicating the begin time of an ISD, so that last element is the begin time of the ISD ending at +infinity.

Note that some information might be displayed before the text of the first subtitle becomes active if, for instance, `tts:showBackground="always"` on a region.

**Comment by TobbeEdgeware** [comment]
@palemieux When using TTML inside an ISOBMFF segment as in CMAF, the endpoints of the timeline for that segment are not 0 and infinity, but given by the time and duration of the sample that contains the TTML. I would therefore like to have the possibility to give the start and end times as parameters to the fromXML function and get events for these times instead of zero. Should I make feature request for that?

**Comment by palemieux** [comment]
`generateISD(tt, offset, errorHandler)` can be called with any value of `offset`, not only the values returned by `getMediaEvents()`.

So, given an ISOBMFF sample covering the interval `[a, b[`, `generateISD(tt, offset, errorHandler)` would be called first with `offset = a`, then in turn with `offset` set to each value of  `getMediaEvents()` that fall in the interval `]a, b[`.

Makes sense?

**Comment by TobbeEdgeware** [comment]
Yes, that should work. Thanks.

**Comment by nicosang** [comment]
Hi,

indeed, it works for the timing question. I have an other question : it seems that regions defined but not used are drawn anyway after the call to renderHTML function. Am I right?

Thanks,
Nicolas

**Comment by palemieux** [comment]
@nicosang The initial value of `tts:showBackground` is `always`, i.e. the region background will always be drawn, even when no text is flowed into it.

`tts:showBackground=whenActive` hides the background when no text is flowed into it.

**Comment by nicosang** [comment]
@palemieux Thanks for the answer. You're right but I have a sample with two regions in which _tts:zIndex_ is defined, _tts:showBackground_ is not defined, so as you said, the value is always. In the html code, i can't see z-index definition, and in this sample, 2 regions are defined at the same area, and according to me (as you may have seen, I'm not an expert :-) ) in the wrong order....

**Comment by palemieux** [comment]
> In the html code, i can't see z-index definition, and in this sample, 2 regions are defined
> at the same area, and according to me (as you may have seen, I'm not an expert :-) ) in the wrong order....

IMSC1 specifies that regions shall never overlap, and thus zIndex is not used.

However perhaps the right approach is to:

* issue a warning
* nevertheless, set css zIndex

Can you file a separate issue?

**Comment by nicosang** [comment]
Once again, you're right! :-) I file, right now, a separate issue.
