### ISSUE TITLE
Element rendered incorrectly due to inherited styling

### ISSUE THREAD

**Issue by bbcrddave** [sandflow/imscJS#12]
This project appears only to set properties which were explicitly set by the contents of the TTML document, with no default properties.

The problem with doing this is that when the document is rendered to HTML and attached to the DOM, the rendered `div` will inherit styling from its ancestors.

An example of this can be seen when testing the initial integration of imscJS into dash.js (https://github.com/Orange-OpenSource/dash.js/tree/feature/imscJSIntegration). The reference player for that project uses bootstrap.css, which sets the CSS `line-height` on `body`. This is ultimately inherited by the rendered div, causing the line-height on the captions to be set incorrectly.

The current parser in dash.js works around this by defining some [default properties](https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/streaming/utils/TTMLParser.js#L573) which are always set and then overridden with values parsed from the TTML as required. It seem like something like this may be needed here.

**Comment by palemieux** [comment]
lineHeight="normal" was incorrectly being inherited. Addressed in PR #13.

Note that imscJS now uses CSS line-height="normal" when TTML tts:lineHeight="normal". This yields more pleasing visual results, but at the risk of more variations across UAs. Alternatively tts:lineHeight could be set to 125% of current fontSize as also recommended in the specification, but this yields visual results that are probably not those expected by the author.

The general recommendation is to always set both tts:fontSize and tts:lineHeight explicitly and together.

**Comment by nigelmegitt** [comment]
I think CSS `line-height: normal;` is exactly coincident with TTML `tts:lineHeight="normal"` so this seems like the correct fix to me.

**Comment by bbcrddave** [comment]
#13 fixes the issue I was seeing, sorry if my analysis confused matters. Thanks!
