### ISSUE TITLE
run QUnit

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [sandflow/imscJS#131]
How do you check unit tests ?
Do you have a specific command line which can offer that ?

I'm currently check to add Travis CI.

**Comment by palemieux** [comment]
The following two sets of units tests are run:

- manually run `src/test/webapp/unit_tests.html`
- manually run `src/test/webapp/gen-renders.html` and compare the output with the [IMSC tests](https://github.com/w3c/imsc-tests) using `script/refpngcompare.py`
