### ISSUE TITLE
Named colors with upper case letters are not recognized

### ISSUE THREAD

**Issue by VincentFTS** [sandflow/imscJS#134]
According to [https://www.w3.org/TR/ttml1/#style-value-namedColor](https://www.w3.org/TR/ttml1/#style-value-namedColor) :

> For the purpose of parsing, a distinction must not be made between lower and upper case.

Yet, for exemple, `Cyan` is not detected.

**Comment by palemieux** [comment]
@VincentFTS Thanks. See the two PRs for your review.
