### ISSUE TITLE
Subtitles somehow overlapping/hiding other HTML elements

### ISSUE THREAD

**Issue by hb-teravolt** [sandflow/imscJS#148]
Hi,

I'm trying to use imscJS on a HTML5 capable TV Set Top Box (STB) and am currently experiencing some weird display corruption - basically the subtitles seem to interfere with other HTML elements, which are not part of the subtitle "target div".

I've attached two screenshots to demonstrate the problem: The first one ("ok.png") shows the videoplayer with enabled subtitles and how it should look (and does locally in my dev environment). In the second ("error.png") showing the state on the actual STB there are some visible issues on the left side:

- the back "<", the i(nfo) and the UT (german abbreviation for subtitle) buttons completely disappeared 
- the rewind "<<" button is party hidden, its left half is missing
- note however that the progress bar at the bottom is not affected at all

The problem seem to pretty much occur by random. You can actually play multiple videos (and/or the same video multiple times) without any problem. And then by chance the problem materializes and stays for some time (videos) and sometimes vanishes again.

Any ideas what could be causing this or possible errors I'm making here in my project? TIA!

Regards,
Harry

![ok](https://user-images.githubusercontent.com/17541808/52940003-c5843480-3365-11e9-9588-7eeaab37c8dc.png)
![error](https://user-images.githubusercontent.com/17541808/52940011-c917bb80-3365-11e9-8cc1-f1203ab76213.png)

**Comment by palemieux** [comment]
@hb-teravolt Thanks for the report. Difficult to debug without access to the player :) Questions/thoughts below:

* is a sample of the IMSC content available?
* have you tried hiding the render div until after it is built: perhaps these are redraw artifacts?

**Comment by hb-teravolt** [comment]
Hi Pierre-Anthony,

thank you for your thoughts on this one. Concerning the "IMSC content sample": the issue does not seem to be connected to the subtitle content (at least in my eyes), because one time a subtitle (entry) causes (starts) the corruption and when you play the same video again it won't occur. Or vice versa. So, really by random.

Will try the hiding trick today to see if this makes any difference.

Cheers,
Harry

**Comment by palemieux** [comment]
@hb-teravolt Any success?

**Comment by hb-teravolt** [comment]
Hi,

so far I was not able to 100% solve this issue, e.g. by hiding the subtitle rendering div during content changes. However, by optimizing the overlapping elements and reducing the time overlapping takes place I managed to considerably reduce the chance of the problem occuring.

Maybe another try would be to force the redrawing/refreshing of the concerned html elements, e.g. by using "transform: translateZ(0)" in the css.

Regards,
Harry

**Comment by palemieux** [comment]
@hb-teravolt Any update? Can imscJS be modified in anyway or additional documentation provided to avoid this issue?

**Comment by hb-teravolt** [comment]
Hi Pierre-Anthony,

no, we were not able to actually fix this issue – but I’m not quite sure if this is related to imscJS at all or some kind of „general“ bug due to the complexity of the app  and/or some glitch of the middleware/hardware of the used Unity STB.
All we managed to achieve was to minify the probabilty the bug will occur by reducing the dom object count on the affected page(s) and some optimizations like hiding the subtitles if on screen menus overlap them.

Regards,
Harald

Von: Pierre-Anthony Lemieux <notifications@github.com>
Gesendet: Samstag, 15. Juni 2019 21:36
An: sandflow/imscJS <imscJS@noreply.github.com>
Cc: Harald Behn <h.behn@teravolt.tv>; Mention <mention@noreply.github.com>
Betreff: Re: [sandflow/imscJS] Subtitles somehow overlapping/hiding other HTML elements (#148)


@hb-teravolt<https://github.com/hb-teravolt> Any update? Can imscJS be modified in anyway or additional documentation provided to avoid this issue?
