### ISSUE TITLE
"auto" not supported by CSS text-emphasis-style

### ISSUE THREAD

**Issue by palemieux** [sandflow/imscJS#158]
https://github.com/sandflow/imscJS/blob/8d458897b38a8d6d2d5b6802637437c4ecb5f436/src/main/js/html.js#L1523

`auto` is not a permitted value of `text-emphasis-style`. Instead, `auto` should correspond to `filled` per CSS defaults:

https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis

**Comment by dkneeland** [comment]
Sample IMSC file:

`<?xml version="1.0" encoding="UTF-8"?>

<tt xml:lang="ja" xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" ttp:frameRate="25" ttp:frameRateMultiplier="1 1" ttp:contentProfiles="http://www.w3.org/ns/ttml/profile/imsc1.1/text" ttp:displayAspectRatio="16 9" ttp:timeBase="media">
  <head>
    <metadata/>
    <styling>
      <style xml:id="style.center" tts:fontFamily="proportionalSansSerif" tts:fontSize="80%" tts:fontStyle="normal" tts:fontWeight="normal" tts:backgroundColor="transparent" tts:color="#DCDCDC" tts:textOutline="black 4%" tts:textAlign="center"/>
      <style xml:id="style.left" tts:fontFamily="proportionalSansSerif" tts:fontSize="80%" tts:fontStyle="normal" tts:fontWeight="normal" tts:backgroundColor="transparent" tts:color="#DCDCDC" tts:textOutline="black 4%" tts:textAlign="left"/>
    </styling>
    <layout>
      <region xml:id="region.after" tts:displayAlign="after" tts:backgroundColor="transparent" tts:origin="5% 50%" tts:extent="90% 45%" tts:luminanceGain="3.0"/>
      <region xml:id="region.vertical.after" tts:displayAlign="after" tts:backgroundColor="transparent" tts:origin="5% 5%" tts:extent="45% 90%" tts:writingMode="tbrl" tts:luminanceGain="3.0"/>
    </layout>
  </head>
  <body>
    <div>
      <p style="style.center" region="region.after" begin="0f" end="1f"><span tts:textEmphasis="auto before">ても美</span></p>
      <p style="style.left" region="region.vertical.after" begin="1f" end="2f"><span tts:textEmphasis="auto after">ても美</span></p>
    </div>
  </body>
</tt>
`
