### ISSUE TITLE
608 conversion: cellResolution width is ignored when setting 1c fontSize

### ISSUE THREAD

**Issue by almson** [sandflow/imscJS#171]
Perhaps you can clarify to what extent IMSC is intended to support 608 closed captions (via SMPTE RP 2052-10), but this is one of two problems we encountered when converting 608 captions to IMSC which might have a solution:

A line with 32 characters (rendered with the monospaceSerif font) is not the same width as 32 cells. In my environment (Linux, Firefox and Chromium), it is slightly narrower for 4:3 content and much narrower for 16:9.

I understand that there is a fundamental difficulty to specify character width in HTML/CSS, but it has a couple of workarounds, such as putting each character into its own div or by supplying a custom webfont.

**Comment by palemieux** [comment]
IMSC 1.2 adds support for web fonts. The latest draft is at:

https://w3c.github.io/imsc/imsc1/spec/ttml-ww-profiles.html

**Comment by almson** [comment]
> the glyph width is effectively set by the font size

Yeah, I figured that.

The problem is there is no standard 608 font, but there is a standard 608 character positioning (the 32x15 grid). I was hoping that cell width would allow emulating the 32x15 grid.

I understand that HTML does not give good tools for controlling character width or spacing. I just wanted to leave this issue here because it does impede 608-to-IMSC conversion and with enough effort there may be a solution.

**Comment by palemieux** [comment]
IMSC specifies reference fonts, so it might be possible to get close:

```
<?xml version="1.0" encoding="utf-8"?>
<tt xmlns="http://www.w3.org/ns/ttml"
    xmlns:ttm="http://www.w3.org/ns/ttml#metadata"
    xmlns:tts="http://www.w3.org/ns/ttml#styling"
    xml:lang="en"
    tts:extent="640px 480px"
    xmlns:ittp="http://www.w3.org/ns/ttml/profile/imsc1#parameter">
  <body >
    <div>
      <p tts:fontSize="33px"
         tts:lineHeight="29px"
         tts:fontFamily="'Courier New'">
                01cdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                15cdefghijklmnopqrstuvwzyzabcdef
      </p>
    </div>
  </body>
</tt>
```

**Comment by almson** [comment]
Here is what your file looks like under Firefox on Linux. It's nowhere close.

![imsc](https://user-images.githubusercontent.com/1435488/71306644-bb9aea00-23eb-11ea-8ad9-e626080986d2.png)

**Comment by palemieux** [comment]
The example above should have specified `tts:fontFamily="monospaceSerif"`, which should alias to Courier on Linux -- assuming the font or an equivalent is available.

**Comment by almson** [comment]
Doesn't entirely help. Your example is missing the concept of the "safe captioning area" which is defined in 608 as a 10% margin at each edge. See last page: https://www.govinfo.gov/content/pkg/CFR-2007-title47-vol1/pdf/CFR-2007-title47-vol1-sec15-119.pdf

![image](https://user-images.githubusercontent.com/1435488/71320817-81981980-24b9-11ea-81c9-42bb8157ab83.png)

**Comment by almson** [comment]
From SMPTE RP 2052-10:2012

> CEA 608 Data is typically authored such that the 32x15 character grid of displayed captions lies within the so called  safe  title  area  of  the  video  picture  area.  SMPTE-TT  regions  are  typically  more  closely  fitting  to  the  contained text and are set in reference to the full video area, so will not necessarily fall within the safe area. Thus converters shall set the ttp:cellResolution attribute so that a 32x15 character grid will lie within the safe area and will place regions based on percentage metrics, so that the default font size of 1c in height, and cell positioning will work as expected. For example, for content authored with an 80%H and 80%V safe title area, an origin=”10% 10%” would be correspond to the top left hand corner of the safe title area, and the required ttp:cellResolution=”40 19”.

**Comment by palemieux** [comment]
Tweaked example:

```
<?xml version="1.0" encoding="utf-8"?>
<tt xmlns="http://www.w3.org/ns/ttml"
    xmlns:ttm="http://www.w3.org/ns/ttml#metadata"
    xmlns:tts="http://www.w3.org/ns/ttml#styling"
    xmlns:ttp="http://www.w3.org/ns/ttml#parameter"
    xml:lang="en"
    tts:extent="640px 480px"
    xmlns:ittp="http://www.w3.org/ns/ttml/profile/imsc1#parameter"
    ittp:aspectRatio="4 3"
    ttp:cellResolution="40 19">
  <head>
    <layout>
      <region xml:id="safe" tts:backgroundColor="black" tts:lineHeight="100%" tts:extent="80% 80%" tts:origin="10% 10%" tts:fontFamily="monospaceSerif"/>
    </layout>
  </head>
  <body region="safe">
    <div>
      <p >
                01cdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                abcdefghijklmnopqrstuvwzyzabcdef
                15cdefghijklmnopqrstuvwzyzabcdef
      </p>
    </div>
  </body>
</tt>
```
Here's what I get on Chrome/Windows:

![0](https://user-images.githubusercontent.com/4871350/71326681-05023c80-24b3-11ea-9f31-d43dfa4955e3.png)

P.S.: I do not claim it is possible to get a perfect conversion.

**Comment by Ryuno-Ki** [comment]
> I understand that HTML does not give good tools for controlling character width or spacing. I just wanted to leave this issue here because it does impede 608-to-IMSC conversion and with enough effort there may be a solution.

Well, there are [some options](https://developer.mozilla.org/en-US/docs/Web/CSS/font-kerning#See_also), but I can't tell, how well they're supported.

As far as I know, W3C is also on GitHub. Feel free to fill issues with them!

**Comment by palemieux** [comment]
Another factor to take into consideration: timed text systems that use a grid for layout are not really responsive, e.g. to aspect-ratio changes, font size changes, etc.
