### ISSUE TITLE
rubyPosition and textEmphasis properties are ignored

### ISSUE THREAD

**Issue by MihailDraghici** [sandflow/imscJS#172]
**Tested XML:**
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tt xml:lang="en" xmlns="http://www.w3.org/ns/ttml" ttp:contentProfiles="http://www.w3.org/ns/ttml/profile/imsc1.1/text" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" ttp:timeBase="media" ttp:frameRate="24" ttp:frameRateMultiplier="1000 1001" ttp:tickRate="1000" xmlns:ebutts="urn:ebu:tt:style" xmlns:itts="http://www.w3.org/ns/ttml/profile/imsc1#styling" xmlns:ittp="http://www.w3.org/ns/ttml/profile/imsc1#parameter" xmlns:ittm="http://www.w3.org/ns/ttml/profile/imsc1#metadata" ttp:displayAspectRatio="16 9">
	<head>
	</head>
	<body>
		<div>
			<!--Test1: Ruby position-->
			<p begin="0f" end="100f" style="default">test1<span tts:ruby="container" tts:rubyPosition="before" tts:rubyAlign="spaceAround"><span tts:ruby="base">base1</span><span tts:ruby="text">text1.1</span></span>text1.2</p>
			<p begin="0f" end="100f" style="default">test2<span tts:ruby="container" tts:rubyPosition="after" tts:rubyAlign="spaceAround"><span tts:ruby="base">base2</span><span tts:ruby="text">text2.1</span></span>text2.2</p>

			<!--Test2: Above and below glyphs-->
			<p begin="100f" end="200f" style="default"><span xml:lang="en"><span tts:textEmphasis="filled dot before">test3</span></span></p>
			<p begin="100f" end="200f" style="default"><span xml:lang="en"><span tts:textEmphasis="filled dot after">test4</span></span></p>
		</div>
	</body>
</tt>
```

**Test 1 (frame 0)**
- **Safari / Chrome**
    - Both ruby texts are displayed **before** the base (the **rubyPosition** field is ignored.)
<img width="808" alt="Screen Shot 2020-01-10 at 5 47 57 PM" src="https://user-images.githubusercontent.com/6793424/72166431-e3211900-33d1-11ea-8c2b-c7668a174b93.png">

- Expected:
    - The first ruby text should be displayed **before** the base
    - The second ruby text be displayed **after** the base
- If we manually set _-webkit-ruby-position: after;_ for the second text:
<img width="808" alt="FAIL_rubyPosition" src="https://user-images.githubusercontent.com/6793424/72166396-d13f7600-33d1-11ea-9f8c-a46ae60019db.png">

**Test2 (frame 100)**
- **Chrome**
        - The **textEmphasis** field **is ignored**
<img width="808" alt="Chrome_FAIL_textEmphasis" src="https://user-images.githubusercontent.com/6793424/72166561-2085a680-33d2-11ea-8f67-0965c7bf95ce.png">

- **Safari**
    - The **textEmphasis** field **is not ignored**. If we inspect this element we can find the following fields: 
        - For test3: _webkit-text-emphasis-style: filled dot; -webkit-text-emphasis-position: over left;_
        - For test4: _webkit-text-emphasis-style: filled dot; -webkit-text-emphasis-position: under left;_
<img width="808" alt="Safari_OK_textEmphasis" src="https://user-images.githubusercontent.com/6793424/72167116-32b41480-33d3-11ea-8bc8-0d2a35b03651.png">

**Comment by palemieux** [comment]
Chrome does not support the `rubyPosition` and `textEmphasis` CSS properties AFAIK.

It looks like Safari supports them using private extensions, which imscJS could support (@MihailDraghici, would that help?)

Both properties are supported by Firefox.

**Comment by MihailDraghici** [comment]
You are right, it looks like Firefox supports both text-emphasis and ruby-position.
On **Chrome / Safari** both of them are displayed correctly if I manually set the fields using **"webkit"** prefix:
    **-webkit-text-emphasis** for text-emphasis
    **-webkit-ruby-position** for ruby-position
Could imscJS support them in Chrome / Safari using private extensions? ("-webkit-" prefix)

**Comment by palemieux** [comment]
@MihailDraghici Please review https://github.com/sandflow/imscJS/pull/173
