### ISSUE TITLE
TextOutline works incorrectly

### ISSUE THREAD

**Issue by dmkyr20** [sandflow/imscJS#174]
Hey, I have used the textOutput option for my IMSC file, but it doesn't work with two <length> parameters as [documented](https://www.w3.org/TR/ttml/#style-attribute-textOutline). Furthermore, I know that CSS doesn't have text-outline, but maybe you can use something like [this](https://stackoverflow.com/questions/4919076/outline-effect-to-text). I have tried this method and the result looks better, as for me. Also, in this case, you can add blur-radius parameter.

https://github.com/sandflow/imscJS/blob/8d458897b38a8d6d2d5b6802637437c4ecb5f436/src/main/js/html.js#L1464

Thanks :)

**Comment by palemieux** [comment]
Can you provide a test file, current render and preferred render?

**Comment by dmkyr20** [comment]
Sure. The IMSC_textOutine_using_shadows file contains emulation ot the textOutline by myself. Using the IMSC_textOutline_using_textOutline file you can see the current render.

Current:
![GitIMSC_issue](https://user-images.githubusercontent.com/24232719/79320800-0993aa80-7f13-11ea-8d43-dfaf587b74b9.png)

Preferred:
![GitIMSC](https://user-images.githubusercontent.com/24232719/79320822-11ebe580-7f13-11ea-8306-f8580f550294.png)


[IMSC_textOutline_issue.zip](https://github.com/sandflow/imscJS/files/4480094/IMSC_textOutline_issue.zip)

**Comment by palemieux** [comment]
Thanks. I have seen text outline typically used with white text and surrounded by a small black outline, so we should make sure this new scheme works well in that case.

**Comment by palemieux** [comment]
@dmkyr20 Does the following capture what you have in mind?

https://codepen.io/palemieux/pen/WNQRqJP

@dkneeland Thoughts on changing `tts:textOutline` as proposed above?

**Comment by dmkyr20** [comment]
@palemieux Hi, yes. I think it looks better than the current text outline render

**Comment by nigelmegitt** [comment]
> https://codepen.io/palemieux/pen/WNQRqJP

That looks like a worthwhile improvement to me, especially experimenting with changing the background and foreground colour to be the same, e.g. white/yellow/lime/cyan/red foreground on white or black background.

**Comment by palemieux** [comment]
@dmkyr20 See PR at https://github.com/sandflow/imscJS/pull/175

**Comment by dmkyr20** [comment]
@palemieux Hey, It looks great. Thanks) Could I ask one more thing. If I add a blur radius for text-outline the text-outline stops working. Could you fix it?

Text-outline documentation: https://www.w3.org/TR/ttml/#style-attribute-textOutline

**Comment by palemieux** [comment]
@dmkyr20 Thanks for the feedback.

> If I add a blur radius for text-outline the text-outline stops working. Could you fix it?

`#textOutline-blurred` is prohibited in IMSC.

What is the objective of using blur?

**Comment by dmkyr20** [comment]
@palemieux Oh, sorry. That's my mistake) Thanks for help)
