### ISSUE TITLE
rubyReserve rendering issue between 1 and 2-line events

### ISSUE THREAD

**Issue by jbaden** [sandflow/imscJS#180]
Hello, 

I've noticed an issue in [imsc1 renderer](http://sandflow.com/imsc1_1/) where the baseline shifts between 1 and 2-line events when tts:rubyReserve is employed.  In my example below, (excerpted from the attached XML), I have used annotation-position: "outside".  

```
		<layout>
			<!-- General Horiztonal Positioning with ebutts:multiRowAlign -->
			<region ebutts:multiRowAlign="start" tts:displayAlign="after" tts:extent="80.000% 80.000%" tts:origin="10.000% 10.000%" tts:rubyReserve="outside" tts:textAlign="center" xml:id="bottom-left-justified"/>
			
            <!-- Descriptive Region -->
			<region tts:displayAlign="before" tts:extent="80.000% 80.000%" tts:origin="10.000% 10.000%" tts:textAlign="center" xml:id="top-center-justified"/>
		</layout>
	</head>
	<body>
		<div>
		    <p begin="100000000t" dur="40000000t" region="top-center-justified">RubyReserve Test</p>
		    <!-- 2-line event with rubyReserve invoked-->
			<p begin="100000000t" dur="20000000t" region="bottom-left-justified">Humpty Dumpty sat on a wall<br/>Humpty Dumpty had a great fall</p>
		    <!-- 1-line event with rubyReserve invoked-->
		    <p begin="120000000t" dur="20000000t" region="bottom-left-justified">All the king's horses...</p>	
```

[rbyReserveTEST.zip](https://github.com/sandflow/imscJS/files/4685789/rbyReserveTEST.zip)

The rendering appears fine between 2-line events, as illustrated in [these tests](https://github.com/w3c/imsc-tests/tree/9e88320cb95bcd6c4b9fe219b680210af43f4439/imsc1_1/ttml/rubyReserve).  It seems this issue is introduced between 1 and 2-line events:

![Event1](https://user-images.githubusercontent.com/25715295/82964256-dfa1bf00-9f79-11ea-96da-d409ef90c649.png)
![Event2](https://user-images.githubusercontent.com/25715295/82964260-e0d2ec00-9f79-11ea-98eb-7026c94cd3d5.png)

Note the jump between 1 and 2-line events when rubyReserve:outside is being employed, which, per the [specification](https://www.w3.org/TR/2018/REC-ttml2-20181108/#style-attribute-rubyReserve), shouldn't occur:

"If the position component is outside, then, if the current block area contains exactly one line area, the both position applies, otherwise the semantics of the before position applies to the first line area of the current block area and the semantics of the after position apply to all other line areas of the current block area."

![correct_rendering](https://user-images.githubusercontent.com/25715295/82964425-49ba6400-9f7a-11ea-95ac-8813a934e8d9.png)

Thanks!

**Comment by palemieux** [comment]
It looks like a bug at https://github.com/sandflow/imscJS/blob/5dcdd8bea9c21590432763f690f023efd161eb2a/src/main/js/html.js#L743, which should also include the case `context.rubyReserve[0] === "outside" && lineList.length == 1`.

**Comment by palemieux** [comment]
@jbaden See PR at https://github.com/sandflow/imscJS/pull/181. Looking forward to your review. I also encourage you to submit test content at https://github.com/w3c/imsc-tests .

**Comment by jbaden** [comment]
Hi @palemieux, 

Thanks for taking a look!

However, from what I can see, there is still relative movement along the y-axis between the baseline of the 1 and 2-line events. 

Also, per your suggestion, I added this test file in imsc1_1/ttml/rubyReserve/rubyReserve004.ttml ([commit](https://github.com/jbaden/imsc-tests/commit/aaa8867fe5f4cf224087a27b82e6c7204d3114a6))

**Comment by palemieux** [comment]
@jbaden Which browser/OS are you using? I do not see a jump at http://sandflow.com/imsc1_1/index.html using Windows 10/Chrome.
![Annotation 2020-06-01 180058](https://user-images.githubusercontent.com/4871350/83468621-30119480-a432-11ea-9da6-d7acb5423f60.png)
![Annotation 2020-06-01 180058-2](https://user-images.githubusercontent.com/4871350/83468622-3142c180-a432-11ea-946c-159c2316053f.png)

**Comment by jbaden** [comment]
My mistake, @palemieux. I wasn't looking at the right place... apologies. 
Confirming all looks good!

**Comment by jbaden** [comment]
My apologies, @palemieux. I was looking at [](http://sandflow.com/imsc1_1/) as opposed to [](http://sandflow.com/imsc1_1/index.html) (not realizing the /index appendage was actually linking elsewhere).  I didn't realize the PR was referencing a different site.  

I took another look at the file and the issue definitely appears to be fixed now.  Thank you!
