### ISSUE TITLE
Apparent double nesting of rubies impacting bouten spacing and baseline shifts (when rubyReserve is used)

### ISSUE THREAD

**Issue by jbaden** [sandflow/imscJS#188]
Hi @palemieux,

After further testing and review, I believe the [rubyReserve issue](https://github.com/sandflow/imscJS/issues/184) you identified may also impact boutens (tts:textEmphasis).

"To polyfill tts:rubyReserve, applyRubyReserve() inserts a zero-width ruby annotation before the first HTML span in each line. This breaks if the first span is itself within a ruby annotation. Probably can be fixed."

In the following XML excerpts & corresponding images generated from IMSC11 Renderer, I've noticed that the baseline shifts when boutens are applied if they are exercised at the very beginning of a line (Example 2). In Example 3, I've added punctuation before the tts:textEmphasis span and the baseline is preserved (as expected with rubyReserve):

Example 1

2-line Horizontal Event without Boutens; with rubyReserve:
`<p begin="100000000t" dur="20000000t" region="bottom-left-justified" ebutts:multiRowAlign="start">強調したい時に使<br/>強調したい時に使</p>`

![noBoutens](https://user-images.githubusercontent.com/25715295/85796255-79ca6380-b6ee-11ea-9250-054ae73cc335.png)

Example 2

2-line Horizontal Event with Boutens + rubyReserve (no preceding character/punctuation before span tts:textEmphasis)
`<p begin="120000000t" dur="20000000t" region="bottom-left-justified" ebutts:multiRowAlign="start"><span style="bouten-filled-circle-outside">強調したい時に使<br/>強調したい時に使</span></p>`

![withBoutens](https://user-images.githubusercontent.com/25715295/85796281-851d8f00-b6ee-11ea-8699-90399f946f57.png)

Example 3

2-line Horizontal Event with Boutens + rubyReserve (with a preceding character/punctuation before span tts:textEmphasis)

`<p begin="140000000t" dur="20000000t" region="bottom-left-justified" ebutts:multiRowAlign="start">〝<span tts:textEmphasis="filled circle before">強</span><span tts:textEmphasis="filled circle before">調</span><span tts:textEmphasis="filled circle before">し</span><span tts:textEmphasis="filled circle before">た</span><span tts:textEmphasis="filled circle before">い</span><span tts:textEmphasis="filled circle before">時</span><span tts:textEmphasis="filled circle before">に</span><span tts:textEmphasis="filled circle before">使</span><br/><span>　</span><span tts:textEmphasis="filled circle after">強</span><span tts:textEmphasis="filled circle after">調</span><span tts:textEmphasis="filled circle after">し</span><span tts:textEmphasis="filled circle after">た</span><span tts:textEmphasis="filled circle after">い</span><span tts:textEmphasis="filled circle after">時</span><span tts:textEmphasis="filled circle after">に</span><span tts:textEmphasis="filled circle after">使</span>〞</p>`

![withBoutnes+character_before_textEmphasis_style](https://user-images.githubusercontent.com/25715295/85796299-8bac0680-b6ee-11ea-9674-ace45a343c77.png)

Test file:
https://github.com/w3c/imsc-tests/pull/94

**Comment by palemieux** [comment]
It looks like the core issue is that imscJS assumed that a span to which `tts:textEmphasis` was applied would never cross a line boundary. WIP fix at #189.

**Comment by jbaden** [comment]
Hi @palemieux, 

Thank you for looking into this!

I just want to highlight that even if I apply tts:textEmphasis within a `<span>` both before **_and_** after the line break, I am still seeing a baseline shift. 

[textEmpahsis_rubyReserveTest_002.xml.zip](https://github.com/sandflow/imscJS/files/4839296/textEmpahsis_rubyReserveTest_002.xml.zip)

```
<p begin="100000000t" dur="20000000t" region="top-center-justified">No Boutens<br/>horizontal</p>
<p begin="100000000t" dur="20000000t" region="bottom-left-justified" ebutts:multiRowAlign="start">強調したい時に使<br/>強調したい時に使</p>
<p begin="120000000t" dur="20000000t" region="top-center-justified">With Boutens（傍点）<br/>horizontal</p>
<p begin="120000000t" dur="20000000t" region="bottom-left-justified" ebutts:multiRowAlign="start"><span style="bouten-filled-circle-outside">強調したい時に使</span><br/><span style="bouten-filled-circle-outside">強調したい時に使</span></p>
```
![noBoutens+rubyReserve](https://user-images.githubusercontent.com/25715295/85902680-7bad2900-b7b9-11ea-9e65-d424c9ccb943.png)
![boutens+rubyReserve](https://user-images.githubusercontent.com/25715295/85902686-7ea81980-b7b9-11ea-8db8-7e82d181919c.png)

The only time I **don't** see a shift is when I have some character/punctuation preceding the first tts:textEmphasis `<span>`

**Comment by palemieux** [comment]
@jbaden As a WIP, I had not deployed this branch to http://sandflow.com/imsc1_1/index.html . I have done so now.

**Comment by jbaden** [comment]
Thank you, @palemieux. 

I have re-reviewed my test files and I'm no longer seeing any baseline shifts.

Thanks again for your help. 

Much Appreciated, 
Justin
