### ISSUE TITLE
Whitespace spans collapse in browser

### ISSUE THREAD

**Issue by vvmnnnkv** [sandflow/imscJS#193]
Hi,

I would like to understand how much is this a desired behavior.
Consider following example:

```xml
<p><span tts:fontStyle="italic">1 </span><span tts:textDecoration="underline"> </span><span tts:fontStyle="bold"> 2</span></p>
```

When parsed by `generateISD`, the resulting elements are: `[1 ][ ][ 2]`
In theory this should be rendered as: <i style="color: blue;">1&nbsp;</i><ins>&nbsp;</ins><b>&nbsp;2</b>
(i.e. include 3 whitespaces of different styles)

Checking result in DOM inspector, all spans are added, however, browser collapses whitespace spans so only the first one is visible.

![image](https://user-images.githubusercontent.com/12518480/96719036-8ff0e380-13b1-11eb-9baf-d3782e705291.png)
![image](https://user-images.githubusercontent.com/12518480/96718950-6c2d9d80-13b1-11eb-8a6e-f1fafb8c4f6d.png)

If this is desired behavior, it would be nice to include this logic in `generateISD` and collapse whitespace spans there (just like whitespace chars are collapsed inside spans).

Thanks!

**Comment by palemieux** [comment]
@vvmnnnkv Apologies for taking so long to get to this.

> In theory this should be rendered as: "1" SP SP SP "**2**"

See the algorithm used by TTML: https://www.w3.org/TR/2006/REC-xsl11-20061205/#white-space-collapse

Essentially, the last two spaces are collapse, resulting in: "1" SP "**2**"

> it would be nice to include this logic in generateISD and collapse whitespace spans there (just like whitespace chars are collapsed inside spans).

Yes. Good idea. I plan to take a stab at it now.
