### ISSUE TITLE
semi-opaque backgroundColor and fillLineGap don't play nicely

### ISSUE THREAD

**Issue by nigelmegitt** [sandflow/imscJS#200]
When the `tts:backgroundColor` applied to `span` elements has some level of transparency more than 0% and less than 100%, and `itts:fillLineGap="true"`, the presence of overlapping background areas gives rise to unexpected effects caused by the application of transparency multiple times.

Example rendering using http://sandflow.com/imsc1_1/index.html:

![image](https://user-images.githubusercontent.com/4988915/101903312-fe7d4100-3bab-11eb-9510-faf8094667d9.png)

I imagine this is going to be very tricky to resolve before proper CSS support for fillLineGap is available, but wanted to log it so it's present as a known issue.

Having looked at the way the padding is extended, I wonder if the use of `Math.ceil()` in `html.js` `applyFillLineGap()` is exacerbating the problem, and why the `px` values are being made integers - perhaps this is a result of implementation experience, since I could not find a specification constraint on `px` units. In some cases the overlap seems to be >1 pixel though, so it could be irrelevant.

<details><summary>Generated by this IMSC document:</summary>
<pre>
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;tt ttp:cellResolution="40 24" ttp:timeBase="media" xml:lang="en-GB" xml:space="default" xmlns="http://www.w3.org/ns/ttml" xmlns:ebutts="urn:ebu:tt:style" xmlns:itts="http://www.w3.org/ns/ttml/profile/imsc1#styling" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:xml="http://www.w3.org/XML/1998/namespace"&gt;
&lt;head&gt;
&lt;styling&gt;
&lt;style ebutts:linePadding="0.5c" tts:textAlign="start" itts:fillLineGap="true" xml:id="S1"/&gt;
&lt;style tts:textAlign="center" xml:id="S2"/&gt;
&lt;style tts:backgroundColor="#00000040" tts:color="#ffffffff" xml:id="S3"/&gt;
&lt;style tts:fontFamily="proportionalSansSerif, default" xml:id="fontFamilyStyle"/&gt;
&lt;style tts:fontSize="150%" tts:lineHeight="120%" xml:id="autogenFontStyle_n_150_120"/&gt;
&lt;/styling&gt;
&lt;layout&gt;
&lt;region tts:displayAlign="after" tts:extent="74.125% 15.652%" tts:origin="12% 79.348%" tts:overflow="visible" xml:id="agr_0_20_39_4_after"/&gt;
&lt;/layout&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;div style="autogenFontStyle_n_150_120 S1 fontFamilyStyle"&gt;
&lt;p region="agr_0_20_39_4_after" style="S2" xml:id="C2_1"&gt;
&lt;span style="S3"&gt;First Line background&lt;/span&gt;
&lt;br/&gt;
&lt;span style="S3"&gt;overlaps second line&lt;/span&gt;
&lt;/p&gt;
&lt;/div&gt;
&lt;/body&gt;
&lt;/tt&gt;
</pre>
</details>

**Comment by palemieux** [comment]
> I imagine this is going to be very tricky to resolve before proper CSS support for fillLineGap is available

Indeed. How do we make progress on CSS fillLineGap?

> but wanted to log it so it's present as a known issue.

Yes. Thanks.

> why the px values are being made integers - perhaps this is a result of implementation experience,

Yes, as I recall this was necessary for some browsers.

**Comment by nigelmegitt** [comment]
> How do we make progress on CSS fillLineGap?

Perhaps creating a WPT test for it would be a good next step, so that implementers have something that a) fails and b) provides a benchmark against which to write code.
