### ISSUE TITLE
Error parsing fontSize with two lengths

### ISSUE THREAD

**Issue by davemevans** [sandflow/imscJS#219]
Given the document below, the following error is produced:

`error: Cannot parse styling attribute http://www.w3.org/ns/ttml#styling fontSize --> 86.100000% 140.000000%`
 
My understanding is that it is valid to represent `fontSize` as a pair of lengths, but perhaps I misunderstood. It appears that within ismcJS the parser assigned in the styling definition assumes a single length.

Should imscJS parse the document, or is there something wrong?

```
<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:smpte="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt" ttp:cellResolution="41 25" xml:lang="en">
    <head>
        <smpte:information smpte:mode="Enhanced"/>
        <styling>
            <style xml:id="ttx" tts:fontFamily="monospaceSansSerif"/>
        </styling>
        <layout>
            <region style="ttx" tts:origin="0.00% 88.00%" tts:extent="100.00% 8.00%" tts:fontSize="86.100000% 140.000000%" tts:lineHeight="2.000000c" tts:textAlign="center" xml:id="region-1"/>
        </layout>
    </head>
    <body>
        <div>
            <p region="region-1" begin="00:00:21.120" end="00:00:23.320">
                <span xml:space="preserve" tts:color="#FFFFFF">&#xA0;&#xA0;</span>
                <span xml:space="preserve" tts:color="#FFFFFF" tts:backgroundColor="#0000003F">&#xA0;CHEERING&#xA0;AND&#xA0;APPLAUSE&#xA0;</span>
                <span xml:space="preserve" tts:color="#FFFFFF">&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;</span>
            </p>
        </div>
    </body>
</tt>
```

**Comment by nigelmegitt** [comment]
@davemevans 2-value `tts:fontSize` is not supported in IMSC. 

In TTML feature terms, as per [7. Supported Features and Extensions](https://www.w3.org/TR/ttml-imsc1.2/#supported-features-and-extensions), [`#fontSize-anamorphic`](https://www.w3.org/TR/ttml1/#feature-fontSize-anamorphic) specifically is _not_ supported, whereas [`#fontSize-isomorphic`](https://www.w3.org/TR/ttml1/#feature-fontSize-isomorphic) _is_ supported.

Translated into English, it means your document is not conformant IMSC.

**Comment by davemevans** [comment]
Thanks @nigelmegitt, useful references as always 👍
