### ISSUE TITLE
linefeeds are not treated as space when xml:space="default"

### ISSUE THREAD

**Issue by mikedo** [sandflow/imscJS#22]
See https://github.com/w3c/ttml1/issues/225

**Comment by palemieux** [comment]
@mikedo I have deployed the proposed fix at http://sandflow.com/imsc1proc/index.html
@bbcrddave This fix (supported by the discussion at https://lists.w3.org/Archives/Public/public-tt/2016Dec/0048.html) significantly affects the rendering of the example at  https://github.com/sandflow/imscJS/issues/6

**Comment by bbcrddave** [comment]
It does. Reading the supporting thread, it is clear that we have made a mistake in our content, so that it is more pleasing to the eye, without realising the effect this would have on the output. We'll correct our workflow. Thanks for the lesson!
