### ISSUE TITLE
PNG sequence rendered differently from HTML

### ISSUE THREAD

**Issue by bbcrddave** [sandflow/imscJS#24]
There seems to be an issue with the png sequence generation in the demo page at http://sandflow.com/imsc1proc/index.html - the png rendering does not match the html rendering. See screen shot below. It looks like the rendering div in the svg container is a different size to the one used for the html render but I have no idea why.

I appreciate this isn't core functionality so its priority is probably low.

![png_seq_bug](https://cloud.githubusercontent.com/assets/5390145/21607221/938f9cde-d1ac-11e6-8a73-575e028c1432.png)

**Comment by palemieux** [comment]
Can you provide a sample file?

**Comment by palemieux** [comment]
Deployed fix that corrects the behavior with the sample at https://github.com/IRT-Open-Source/irt-ebu-tt-d-application-samples/blob/master/ttml/space-preserve-001-ttml.xml

**Comment by bbcrddave** [comment]
It's better, but still not right. The width looks correct now but I think the height is wrong.

![sedlobortis](https://cloud.githubusercontent.com/assets/5390145/21637687/f789dc78-d25f-11e6-89ec-b7765d6f95d6.png)

Source is [sedlobortis.txt](https://github.com/sandflow/imscJS/files/684277/sedlobortis.txt)

**Comment by bbcrddave** [comment]
As an aside, I think when you do:
```
svg.setAttribute('width', vdiv.clientWidth);
svg.setAttribute('height', vdiv.clientHeight);
```
you need to add `+ 'px'` to set the right unit type on the `SVGLength`?

**Comment by palemieux** [comment]
@bbcrddave  Added 'px'. Looks good in Chrome and Firefox on my side.

**Comment by bbcrddave** [comment]
It is working correctly in Firefox, but in Chrome (55, Win7) the computed clientHeight for rdiv is still 563px, which seems to be causing the incorrect PNG rendering. The screenshot below shows that, whilst there is no gradient fill in the extra space, the dimensions are incorrect and hence the text fails to scale correctly.

![screens](https://cloud.githubusercontent.com/assets/5390145/21674018/c5fc16ac-d323-11e6-978c-17db9b96dfc5.png)

**Comment by palemieux** [comment]
Here's what I get using Chrome 55. Any chance the browser cache might be stale? Just exploring all possibilities.

![0](https://cloud.githubusercontent.com/assets/4871350/21686880/d992297a-d31b-11e6-926a-9a0616bab655.png)

**Comment by bbcrddave** [comment]
Just tried it in an incognito window and also in Canary and get the same result as previously :disappointed:

**Comment by palemieux** [comment]
@bbcrddave Is the zoom level !== 100%?

**Comment by palemieux** [comment]
height and width of the exported PNG now set explicitly. Fixes the output bug when using a zoom level !== 100% in Chrome.

**Comment by bbcrddave** [comment]
That change does seem to have fixed the issue - thanks!
Zoom level is 100% though. :confused:
