### ISSUE TITLE
Cannot see PNGs in case of IMSC1.0 image profile

### ISSUE THREAD

**Issue by cfadamp** [sandflow/imscJS#28]
Hello!

I could not see the PNG images from an IMSC1.0 image profile (http://www.w3.org/ns/ttml/profile/imsc1/image) file. Are the sample files are wrong or imscJS does not support this kind of IMSC files yet?

Attached the sample MXF as well as the XML+PNGs.

Thanks,
Adam

[IMSC1.0-image_profile.ZIP](https://github.com/sandflow/imscJS/files/713665/IMSC1.0-image_profile.ZIP)

**Comment by palemieux** [comment]
The [demo application](sandflow.com/imsc1proc/index.html) currently assumes that the images referenced in the document are available over http. The application could be extended to support locally sourced images. One option is to require that the IMSC1 document and the referenced images be wrapped in a single ZIP file. Other options?

**Comment by cfadamp** [comment]
Hi Pierre,

thanks for the answer! I am good with the http option for now.

Best,
Adam
