### ISSUE TITLE
display artifacts after animation

### ISSUE THREAD

**Issue by mikedo** [sandflow/imscJS#39]
[Example document provided privately.]

**Comment by palemieux** [comment]
Three `<p>` flow into the region at the time it exhibits the artifact.
Each `<p>` contains a `<span>` with a black background. The region is
not tall enough to accommodate the three `<p>`. In fact it is just
tall enough to accommodate two `<p>` plus a sliver of the third.

The artifact is that sliver showing.

Potential solutions :
- make the region taller if the first `<p>` is intended to be shown
- do not display one of the three `<p>`
