### ISSUE TITLE
EBU-TTD line padding not rendered

### ISSUE THREAD

**Issue by TobbeEdgeware** [sandflow/imscJS#46]
The sample http://vm2.dashif.org/dash/vod/testpic_2s/sub_swe_short.xml does not render the EBU-TTD line padding specified. Is there any error in the syntax, or is there an issue with imscJS?

The styles look like

      <style xml:id="s1" tts:color="#00ff00" tts:backgroundColor="#000000" ebutts:linePadding="0.5c"/>

**Comment by palemieux** [comment]
`ebutts:linePadding` must be applied to `<p>`

**Comment by TobbeEdgeware** [comment]
I see. Makes sense. I updated the first cues in the sample, but now I get far too much padding, not just half a character but ~8 characters on each side. Is there anything else that is wrong?

**Comment by palemieux** [comment]
> Is there anything else that is wrong?

Try it at http://sandflow.com/imsc1proc/index.html and tell me if it looks as intended.

**Comment by TobbeEdgeware** [comment]
I did before posting. 
<img width="798" alt="screen shot 2017-05-11 at 00 34 32" src="https://cloud.githubusercontent.com/assets/16939725/25924182/ba1733e6-35e1-11e7-835a-07e7bb2d4bd1.png">

I even removed the `<span>` I had before so that there were no whitespace in the paragraph:

         <p xml:id="sub00000" begin="00:00:00.000" end="00:00:01.000" style="s1">swe : 00:00:00.000</p>

**Comment by palemieux** [comment]
`tts:backgroundColor` needs to be applied to the span only, otherwise the entire region background will be colored.

**Comment by TobbeEdgeware** [comment]
I find it strange that the background can leak from the paragraph into the whole region, but if I change it I can get the behavior I want.

**Comment by palemieux** [comment]
@TobbeEdgeware My understanding is that the paragraph width fills the entire region's width, and thus the background of the paragraph is that of the region.
