### ISSUE TITLE
No render if begin and end attributes are prefixed using namespace

### ISSUE THREAD

**Issue by jeremco** [sandflow/imscJS#48]
Using the following xml : 
[test_XML.txt](https://github.com/sandflow/imscJS/files/992918/test_XML.txt)

The text is not rendered, because begin and end are not found.
In docs.js , function processingTiming, the attributes searched is 'begin', whereas in this case, attribute is tt::begin. 
It is the same for end. 

The xml seems ok.

**Comment by palemieux** [comment]
From https://www.w3.org/TR/xml-names/#defaulting : _the namespace name for an unprefixed attribute name always has no value_.

`begin` and `end` are unprefixed in TTML.

**Comment by jeremco** [comment]
Hi 
Thanks for your answer. 
We'll check our equipments and give a feed back to our providers to be compliant with the TTML.

Jérémie
