### ISSUE TITLE
imsc 1.0.0-beta.3

### ISSUE THREAD

**Issue by nicosang** [sandflow/imscJS#49]
Hi,

I have a problem with the new npm package : the src folder is empty.... :-(

Regards,
Nicolas

**Comment by palemieux** [comment]
I have just executed ` npm install imsc` and ended-up with:

![capture](https://cloud.githubusercontent.com/assets/4871350/26006903/19b01496-36f3-11e7-896f-45417f4596e9.PNG)

**Comment by nicosang** [comment]
Sorry, it was an error ....it's good now. :-(

Nicolas
