### ISSUE TITLE
error: Cannot parse styling attribute http://www.w3.org/ns/ttml#styling color --> fuchsia

### ISSUE THREAD

**Issue by jettoblack** [sandflow/imscJS#50]
"fuchsia" is listed as one of the namedColors in the TTML spec (same RGB value as "magenta") but is not working here.  Is "fuchsia" not permitted in IMSC 1.0?

**Comment by palemieux** [comment]
`        fuschia: [255, 0, 255, 255],` at `util.js` should read `        fuchsia: [255, 0, 255, 255],`

Will fix in a few mins.
