### ISSUE TITLE
line height artifacts with whitespace

### ISSUE THREAD

**Issue by mikedo** [sandflow/imscJS#55]
When whitespace is present on `<p>`, it alters the line height even though no glyph is output.
See the attached file. The four `<p>` differ as follows (other than time):

1 & 2 – tts:lineHeight not set
3 & 4 – tts:lineHeight set to 100% (whatever “normal” is)
1 & 3 – no direct content in `<p>` (all in the <span>)
2 & 4 - a single trailing space between the `</span>` and `</p>`

When whitespace is present, the line height increases and shows a line gap. If there is no whitespace on the `<p>` there the line height is as expected.

FYI, newlines have the same affect as the space.
 
[lineHeight.zip](https://github.com/sandflow/imscJS/files/1068729/lineHeight.zip)

**Comment by palemieux** [comment]
Deployed at http://sandflow.com/imsc1proc/index.html

**Comment by palemieux** [comment]
It looks like this is caused by CSS/UA treatment of spaces before explicit `br`.
