### ISSUE TITLE
process unit tests via command line

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [sandflow/imscJS#61]
I'm looking on this project, and try to run qunit tests via the command line.
I add the dependency to `grunt-contrib-qunit` and some code to run
`npm test` (just after `npm install`)

Based on this [commit](https://github.com/MarcAntoine-Arnaud/imscJS/commit/36edb6e32cdd023bdb2ef6e375838eb594865808) I got this message:
```
Running "qunit:files" (qunit) task
Testing ./src/test/webapp/unit_tests.html 
>> PhantomJS timed out, possibly due to:
>> - QUnit is not loaded correctly.
>> - A missing QUnit start() call.
>> - Or, a misconfiguration of this task.
Warning: 1 tests completed with 1 failed, 0 skipped, and 0 todo. 
0 assertions (in 0ms), passed: 0, failed: 0 Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
```

Do you know how to "start" the QUnit module ?

**Comment by palemieux** [comment]
Running QUnit from the command line requires PhantomJS, which is a headless user agent based on WebKit.

QUnit tests can otherwise be run by executing `unit_tests.html` .
