### ISSUE TITLE
Clarify that div must be attached to DOM before calling renderHTML(isd, div)

### ISSUE THREAD

**Issue by bbcrddave** [sandflow/imscJS#7]
Line padding appears to be implemented using CSS box-shadow. In order to apply the correct colour to the box-shadow, the parser calls `window.getComputedStyle`. However, `getComputedStyle` only works if the element whose style should be computed is ultimately attached to the DOM.

If you attempt to render the ISD to a div which is not attached to the DOM it is mostly rendered correctly but the padding will be applied with no colour information. The default colour for the box-shadow is browser dependent but is usually CSS `color`, which is unlikely to be the author's intention.

Either the documentation should mention the requirement that the div be attached to the DOM prior to calling `renderHTML`, or the implementation should be changed such that this is not required (ie don't use `getComputedStyle` to determine the box-shadow colour).

**Comment by palemieux** [comment]
> or the implementation should be change such that this is not required (ie don't use getComputedStyle to determine the box-shadow colour).

Attaching to the DOM is also currently required in order to programmatically determine line breaks so that line padding and multirow align can be applied (since CSS does not support them)... unless there is another approach.
