### ISSUE TITLE
Origin/extent information does not take effect from <p> section

### ISSUE THREAD

**Issue by cfadamp** [sandflow/imscJS#70]
Hello,

attached is a sample problematic file.  The origin and extent information are not stored under styling \ region but in the div \ p sections. The imscJS library positioned all the subtitle spots to the 0,0 (upper left corner), I think because it ignores the origin/extent values from <p>. My question is that should this work? Or does the spec clearly state that the origin/extent data in <p> must be ignored?

Thanks,
Adam

[caption.zip](https://github.com/sandflow/imscJS/files/1454784/caption.zip)

**Comment by palemieux** [comment]
`tts:origin` and `tts:extent` apply only to `region` in IMSC1 (and TTML1), and are ignored when specified on `p` and `div` elements.

See https://www.w3.org/TR/ttml1/#style-attribute-extent .

**Comment by cfadamp** [comment]
Thank you Pierre, I was not sure when reading this section of the spec. You can close this one! There are some _funny_ implementations of TTML generating around the world...

Best,
Adam
