### ISSUE TITLE
Overlapping lines

### ISSUE THREAD

**Issue by spoeschel** [sandflow/imscJS#77]
When I render the [attached file (please rename to `.xml`)](https://github.com/sandflow/imscJS/files/1736324/double_height_test.xml.txt), the second subtitle is rendered with overlapping lines:

![11](https://user-images.githubusercontent.com/16134158/36373746-6272c016-1569-11e8-97b9-6f32dc841755.png)

However my expectation was that these lines don't overlap, as the `tts:lineHeight` is `125%` here and "relative to this element's font size". I hope I didn't miss something...

I tested with http://sandflow.com/imsc1proc and:
- Firefox 58.0.2 @ Win7
- Chrome 64.0.3282.167 @ Win 7
- Chromium 64.0.3282.140 @ Ubuntu MATE 16.04

**Comment by palemieux** [comment]
`tts:lineHeight` is computed at the time it is applied. It is thus relative to `tts:fontSize="160%"` and not `tts:fontSize="200%"`

**Comment by spoeschel** [comment]
You're right; therefore the resulting line height is too small here and the rendering is correct. Sorry!
